FROM node:16-alpine as build_stage

RUN mkdir -p /app
WORKDIR /app
COPY reactapp/package.json .
RUN yarn
COPY reactapp .
RUN yarn build

FROM nginx:1.16.0-alpine

COPY --from=build_stage /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]