"""Initial migration

Revision ID: 21bbeb8bacee
Revises: 
Create Date: 2022-05-26 05:11:46.127731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bbeb8bacee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'fema', name='sexenum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('admission_hour', sa.Time(), nullable=True),
    sa.Column('hpi', sa.Text(), nullable=False, comment='History of the Present Illness / HMA'),
    sa.Column('waiting_vacancy', sa.Boolean(), nullable=True, comment='Aguardando vaga na Regulação'),
    sa.Column('regulation_code', sa.String(), nullable=True, comment='Número de registro da regulação'),
    sa.Column('pendings', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('evolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True, comment='Evolução do paciente com exame físico e sinais vitais'),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evolutions')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
