"""Add mothers name to patient model

Revision ID: 49f6dfaa400d
Revises: d13d4be1fa86
Create Date: 2023-01-22 16:41:59.297612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f6dfaa400d'
down_revision = 'd13d4be1fa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('mother_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'mother_name')
    # ### end Alembic commands ###
