"""add professional who finished an internment

Revision ID: af9b603d8430
Revises: 24a0124aec13
Create Date: 2022-12-21 16:03:05.294494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9b603d8430'
down_revision = '24a0124aec13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internments', sa.Column('finished_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'internments', 'users', ['finished_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internments', type_='foreignkey')
    op.drop_column('internments', 'finished_by_id')
    # ### end Alembic commands ###
